language: go
sudo: required
services:
- docker
go:
- 1.5.1
script:
- go get github.com/mitchellh/gox
- gox -osarch="linux/amd64" -output="docker/bjornbot_linux"
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- cd docker
- docker build -t bjorn248/bjornbot .
- docker push bjorn248/bjornbot
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: RUWfn+lErvOImr0S6MMxbSTIHCgPhgaf+danLvbI5O6bOTLpLqrrPjvvhFSY8ca4hLz1noDP75O1swBr1iCbFhzfjWwkKl7tmfjbNtLoH+GmRXrNay2aLHnfGOafdus1VarvqGcghv8RpkEJkdYXMFtZsjDugkHGqdV7xWceWq5SueM8zUUb58X9+mxJ45a3RH3dz4UOfl6KGPqx0i+DP128O3l84eAOjR12uFz73CsHzP14wVVigeb+3k5fbqeLELAJe4KPgJhvuuEzGGq3Bebz0YF5xaxo/3nmxC8oSogyyqKv7rtmO9jTidrQo1xNSrS2LMv0WzsPSI/F13gF/y2B2pR62b5OwawkeMNyHKBM5nGiOJ8vOrknTjcRt2wsYuLHtAoHosU7fDAId8o6OAzmLjaFjEM9xZRZGNWKpPqCNkqUx296IQ+zKX386COhNkb8XHsWvPOQ8rZJ+SSnyG9ybHH+Zpv61zN439S+Pvo5Wnu3iDj7/Po6/nb6kROLSUsdZs8V5lEAXI7nDYqck2/W3xgEkR6TL6sJM0KjREICSRt9UYuln7vfu3H5hOKu+gc9vBD0K4GWa7KgUr1z8Ronkqr2eGfSgcti13BftClKy0aPKv4vAUbxVjAXtrUPZTnURw4gwesgHPwuHDyJ79YYRD3ln9DmtGyMi9WFtKQ=
  app: bjornbot
  on:
    repo: BjornTwitchBot/BjornBot
