language: go
sudo: required
services:
    - docker
go:
    - 1.5.1
script:
    - GOOS=linux GOARCH=amd64 go build -o ./docker/bjornbot_linux *.go
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - cd docker
    - docker build -t bjorn248/bjornbot .
    - docker push bjorn248/bjornbot
